[workspace]
members = ["eyeball", "eyeball-im"]

[workspace.dependencies]
futures-core = "0.3.26"
readlock = "0.1.5"
tokio = { version = "1.25.0", features = ["sync"] }
tokio-stream = { version = "0.1.11", default-features = false, features = ["sync"] }
tracing = { version = "0.1.37", default-features = false, features = ["std"] }
