[package]
name = "eyeball-im-util"
version = "0.2.1"
edition = "2021"
description = "Helpful utilities for `eyeball-im`."
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
eyeball-im = { version = "0.2.0", path = "../eyeball-im" }
futures-core.workspace = true
imbl = "2.0.0"
pin-project-lite = "0.2.9"

[dev-dependencies]
stream_assert.workspace = true

[lints]
workspace = true
