[package]
name = "eyeball-im"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
description = "Observable collections based on the `im` crate."
repository = "https://github.com/jplatte/eyeball"

[package.metadata.docs.rs]
all-features = true

[dependencies]
futures-core.workspace = true
im = "15.1.0"
tokio.workspace = true
tokio-stream.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
