name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests (Rust stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features

  docs:
    name: Check documentation (Rust stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: "-D warnings"

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt -- --check

  test-miri:
    name: Run tests with miri (Rust nightly)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - uses: Swatinem/rust-cache@v2
      - run: cargo miri test --all-features
        env:
          # Enable Tree Borrows, Stacked Borrows is weirdly restrictive
          # https://github.com/jneem/imbl/issues/59#issuecomment-1569746186
          MIRIFLAGS: "-Zmiri-tree-borrows"

  clippy:
    name: Run clippy (Rust nightly)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features -- -D warnings

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.4
